### ISSUE TITLE
FrankerFaceZ for Twitch doesn't work

### ISSUE THREAD

**Issue by Gravarty** [rmottola/Arctic-Fox#8] opened 2019-01-07 18:52 UTC
I know that this script (added it via Greasemonkey) doesn't work on Pale Moon 27 as well (requires 28) but maybe it's possible to backport the required stuff to 27 to make it work. Best browser so far for OS X Snow Leopard and i hope it stays for a long time :)

**Comment by wicknix** [comment] 2019-01-09 00:40
Thanks for pointing it out. We know the JS in AF is a bit outdated, and may cause some issues going forward. Riccardo has been doing some work towards getting it more up to date. Hopefully it can be done. Can you do us a favor and try that script in the last supported FF (45.9esr i believe) for 10.6? Would be good to know if it does or doesn't work for reference as to which version to possibly pull code from.

**Comment by rmottola** [comment] 2019-05-16 15:25
Did you try latest AF 27.17? Maybe it was fixed by chance.

**Comment by rmottola** [comment] 2019-09-03 13:42
any updates on further tests? FF45 or FF49 as requestred?
In the meanwhile .18 is out which fixes a regression introduced past year... could you try?

**Comment by rmottola** [comment] 2023-01-09 08:49
@Gravarty did you by chance test on FF45 for a comparison?
In the meanwhile, you could try v40.1 - it does improve JS quite a bit compared to 27.x series... maybe you are lucky.

**Comment by rmottola** [comment] 2023-06-28 23:59
no answers... suppose the issue is either solved or the reporter is not interested anymore.

**Closed by rmottola** 2023-06-28 23:59 UTC
